### ISSUE TITLE
[Scan FB] ScanFB的訂單在成立之前需判斷fbcommenttable

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1140]
server在成立訂單scan fb之前
先檢查getFBCommentTable的同一個fbcid是否status == 0
為0才可以建立 
(若沒有此fbcid row，或status > 0不可建立)

**Comment by cmacma7** [comment]
Fixed on BN at version 1758.

**Comment by cmacma7** [comment]
Hi Peiching, to check status of fbcomment table, please use  actions.server[i].method = "checkFbCommentStatus", and actions.server[i].data.value = 0   
this will check the commentTable status field to make sure the status is equal 0 in order to put the order.
you can set actions.server[i].value to any number if you want to check the value to this number. If it is equal , then order will be sent, otherwise you will receive data.err = "ERR_DIRTY_WRITE"

**Comment by peichingliao** [comment]
已套用到scan fb程式碼
