### ISSUE TITLE
[membership]刪除會員後，重新整理，被刪除的會員資料又出現了。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1638]
重現問題的步驟
步驟1.勾選某一位會員，進行刪除。
步驟2.重新整理網頁。
步驟3.剛剛被刪除的會員資料，又回到頁面上。

**Comment by anitalo73** [comment]
清除一下我勾的那兩項，刪除的項目就會去掉了

接下來會禁止客戶刪除會員資料

![image](https://user-images.githubusercontent.com/35478230/47479179-c9dc8d00-d85e-11e8-9e84-534e6132ebbe.png)

**Comment by cmacma7** [comment]
Covered by disable the delete button of membership table.  We do not allow delete of member in admin case because the cache cannot sync between devices. Also if delete row, then transactions related to this row will not be able to fetch the correct customer information. So we decided to disable the delete button. However, the Sales mode will always fetch all rows instead of cache because the role of Sales can change anytime, so there is no reason to cache.
