### ISSUE TITLE
[widget][validate] validate need to pass the old widget context before editing, so that the widget editor can know which context has been changed

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#368]

**Comment by cmacma7** [comment]
The validate() function has extend to have 3rd parameter which is the kept widget context before editing.

.validate(newContext, newSchema, oldContext);

**Comment by cyen1121** [comment]
確認 最新版本修正成
Callback of validate added. function validate(context, schema, context_before_editing, callback)
 Function is called by system when widget save to server (edit or create new widget). The system call this function to make sure user has enter correct information in the editor. If information is not enough or error, function will return false, otherwise true. If false, the widget will not be created or modified. context_before_editing is the original context before any change in the editor, it is useful to compare the change before and after editing.
The module use context and schema to valid all the fields that user enter. Most of the cases, context is good enough to validate the fields.
function must call callback with result. true means successful, otherwise false means the system should not do any next step with this widget, for example, save this widget to the server.
