### ISSUE TITLE
需要isOwner & isAdmin function去判斷Widget能夠開放的權限

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#416]

**Comment by cmacma7** [comment]
// function return whether current user own the widget.
// if includeAdmin is true, then admin of the station of the widget also counts as owner.
// if includeAdmin is not true, function return true only if user is owner.
function isOwner(obj, includeAdmin);

// function isAdmin, return true if the user is admin, not owner! 
function isAdmin(obj);

fix on BN

**Comment by cmacma7** [comment]
David might need to consider :
 looks like isAdmin() is also need in your logic, because if you are admin, in order widget you will go to received mail when user click history order button. However, since you are not owner, so you will not receive orders. As the result, if user isAdmin(), he/she will go to the sent mail of the widget when click history orders.

**Comment by cmacma7** [comment]
Has been fixed for a long time...
