### ISSUE TITLE
國豪研究臉書自動回覆功能

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#504]

**Comment by ghyu65** [comment]
測試了下面幾個都不行, http://fbmassmessage.thinkitpro.com/, http://autorelaxed.com/, https://bonbg.com/2014/08/adrsfb/, 看 autorelaxed 原本就是專門做這個功能, 但也寫 "We have temporarily disabled auto replies for private messages because of technical difficulties. We are sorry for the inconvenience." 看起來 FB 是已經把這條自動回覆的路堵死了~
下面有篇文章  https://chrishardie.com/2014/08/facebook-messages-autoresponder/ 也是在討論這個需求, 目前看起來私訊這一塊是無解的~

**Comment by ghyu65** [comment]
因為現在訊息其實也還不多, 我會隨時留意先手動回覆即可~

**Comment by ghyu65** [comment]
因為研究之後靠外部程式做不到自動留言,  而粉絲團倒是有自動回覆功能可用, 但是一般都是問設定或系統問題, 也無法自動回覆達到效果, 目前就先決定人工定時查看回覆, 我會常常 monitor, 需要 call help 再轉出來通知相關的同仁~
