### ISSUE TITLE
[System] 某些形式的網址無法正常開啟

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#611]
http://store.tagfans.com/index_noAppCache_v1.1.925.html#page_join?o=296&id=896&viewType=station

a. chrome可開啟
b. IE8 開啟畫面有問題 ..................(Bug 1)

http://store.tagfans.com/index_noAppCache_v1.1.857.html#page_station?o=271
c. chrome 無法開啟..................(Bug 2)
d. IE8 無法開啟 ..................(Bug3)

**Comment by cmacma7** [comment]
We are not plan to support IE8... this browser .... too old to support.
Regarding old version's url that people still use ... this problem is caused by server side software already move to new version, as the result, the old version client code does not work anymore, need to redirect to the new version.

**Comment by peichingliao** [comment]
因為我的windows 7 升級IE失敗，很神奇，所以還是用IE8
我再試試看如何升級..

仍有(bug2)
