### ISSUE TITLE
[消費紀錄][統計總結] 展開A訂單點<，再展開B訂單點<，無作用

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#885]
[Scenario]
1. 老闆至 消費紀錄/收件訂單/統計/統計總結
2. 展開A訂單，點< =>成功叫出menu
3. 再展開B訂單，點<

[Result] 無作用

**Comment by cmacma7** [comment]
Problem caused by the Div inserted into join dialog is removed when join dialog is empty() to add new content. The empty() function will remove all data and event handler of a div. 
We change to use detach() to prevent the remove of data and event handler. 
Hint, to view all event of an element, you can see $._data(div, "event").

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
---

進入統計總結/點選A訂單號碼/在A大版訂單上按 < /關閉大版訂單/再點一次A訂單號碼/在A大版訂單上再按一次 <
=>功能烈都可以正確顯示
