### ISSUE TITLE
[店內點餐][銅盤] 填寫第2次客戶滿意度調查表，則"繼續"&"返前"btn未顯示

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#925]
[Scenario]
0. 下載 tagfans點餐系統 測試APP
1. 進入銅盤點餐系統/客戶滿意度調查表/開始填寫
2. 填寫過程中，可以按"繼續"、"返前"，或是手動滑動頁面
3. 寄送
4. 馬上再點一次"開始填寫"

[Result] "繼續"、"返前"的btn沒有顯示

**Comment by gameflierHao** [comment]
Fixed in :  http://store.tagfans.com/
Version : 1.1.1522

參考測試位置 : http://store.tagfans.com/#page_join?o=1145&id=9173&viewType=station

Revision: 1524
Author: zhanghaowu
Date: 2016年11月14日 上午 11:22:59
Message:
[店內點餐][銅盤] 填寫第2次客戶滿意度調查表，則"繼續"&"返前"btn未顯示 #925

當送出後 會將 繼續 &返前 hide掉

## 因此 開始填寫 點擊後要再將 繼續 &返前 show

Modified : /nodejs/bn/widgets/Widget/Opinions Collection/customerForm#FullSinglePage.js

**Comment by Iris926** [comment]
已驗證無誤。
