### ISSUE TITLE
新版商店，商品出現在不該出現的頁面

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#945]
此頁，原本只有重要公告一篇說明，沒有商品。但今天發現商品出現在頁面內。本商品的建立流程是由商店首頁的右上角，點選商品符號==>新增商品，所建立。因此不會出現在這個重要公告頁面內。
http://store.tagfans.com/#page_join?o=3797&id=20933&viewType=station

另外，此商店另有兩個商品(建立的方式同上)，今天亦出現在【服務據點】頁面內。今日從這個頁面把商品刪除後，再也找不到了。服務據點頁面如下:
http://store.tagfans.com/#page_join?o=3797&id=20936&viewType=station

**Comment by kevinyu75** [comment]
複製方式: 直接增加新商品，就會出現在「服務據點」這個頁面。(與tag內容無關。)

**Comment by cmacma7** [comment]
Fix in version 1518. SVN#1518
Problem cause by global.stationInfo still keep in previous page. For example, if you enter a station page, then back to product page. The global.stationInfo is still the station page. As the result, when handleDeploySend try to create the note, it think it is a station page with global.stationInfo.id equal to something, instead of undefined.

**Comment by cmacma7** [comment]
To reproduce the problem
1. Enter a store that it's style is set to product page
2. click left-top menu, choose a page ( for example page A).
3. click back from the page, then you will back to product page again.
4. now create a product by click right-top icon, select create new product.
5. create the product, then you will find your product appear in page A, instead of inside the product page.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1522
[Result] Fixed
